"use client";

import Link from "next/link";
import "./globals.css";
import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Create Next App222",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);
  useEffect(() => {
    fetch("http://localhost:9999/topics")
      .then((res) => res.json())
      .then((result) => setTopics(result))
      .catch((e) => console.log(e));
  }, []);

  console.log(topics);

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          <li>
            <Link href="/read/1">html</Link>
          </li>
          <li>
            <Link href="/read/2">css</Link>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <button>Delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
