import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App222",
  description: "Generated by create next app",
};

// ⭐️ async 선언은 필수 이다. fetch에서 await를 사용하기 위함
export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:9999/topics", {
    cache: "no-cache",
  });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((item) => (
            <li key={item.id}>
              <Link href={`/read/${item.id}`}>{item.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <button>Delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
